### ISSUE TITLE
【求助】配置成功后，链接服务器ip地址 显示502

### ISSUE THREAD

**Issue by CapAllen** [ibisheng/deploy#3]
按照步骤一步步来的，中间也没有报错，所有模块安装完都是done的状态。
这是dockers
![图片](https://user-images.githubusercontent.com/35265537/62605649-206a1200-b92d-11e9-95b7-abae73717b27.png)
但输入服务器ip地址，显示502
![图片](https://user-images.githubusercontent.com/35265537/62605713-41cafe00-b92d-11e9-8d54-fa68e6a6f3ee.png)

**Comment by xiehongan123** [comment]
1. mongodb结点没有起来。可以看看什么原因
2. 在解决了mongodb之后可以运行 upNodes.sh把结点重新启动

在 2019-08-07 16:06:46，"Shengjie Jia" <notifications@github.com> 写道：


按照步骤一步步来的，中间也没有报错，所有模块安装完都是done的状态。
这是dockers

但输入服务器ip地址，显示502
